EStore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
    path("product/", include("products.urls", namespace="product")),
    path("category/", include("category.urls", namespace="category")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include('orders.urls', namespace="order")),
    path("about_us/", views.about_us, name="about_us"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_condition/", views.terms_condition, name="terms_condition"),
    path("payment_policy/", views.payment_policy, name="payment_policy"),
    path("shipping_policy/", views.shipping_policy, name="shipping_policy"),
    path("return_policy/", views.return_policy, name="return_policy")



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate"),
    # path("forgotpass/", views.forgotPassword, name="forgotPassword"),
    # path("password_validate/<uidb64>/<token>", views.password_validate, name="password_validate"),
    # path("resetPassword/", views.resetPassword, name="resetPassword")
]

carts/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remote_cart, name='remove_cart'),
    path('checkout/', views.checkout, name="checkout"),
]

microstock/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

# Create your models here.

class UserAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not username:
            raise TypeError("User most have a username")
        if not email:
            raise TypeError("User most have an email")
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            password = password
        )
        user.set_password(password)
        user.save(using = self._db)
        return user
    
    def create_superuser(self, email, first_name, last_name, password, username):
        user = self.create_user(
            email = self.normalize_email(email),
            password=password,
            username=username,
            first_name=first_name,
            last_name=last_name
        )
        user.is_admin = True
        user.is_active = True
        user.is_superadmin = True
        user.is_staff = True
        user.save(using=self._db)

class User(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=250, unique=True)
    phone_number = models.CharField(max_length=50)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    objects = UserAccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "last_name", "first_name"]

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, add_label):
        return True

accounts/forms.py
from django.forms import ModelForm
from .models import User
from django import forms

class registrationsform(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Enter Password", 'class': "form-control"
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Confirm Password", 'class': "form-control"
    }))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password']
    
    def __init__(self, *args, **kwargs):
        super(registrationsform, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = "Enter First Name"
        self.fields['last_name'].widget.attrs['placeholder'] = "Enter Last Name"
        self.fields['email'].widget.attrs['placeholder'] = "Enter Email Address"
        self.fields['phone_number'].widget.attrs['placeholder'] = "Enter Phone Number"


        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    
    def clean(self):
        cleaned_data = super(registrationsform, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('password deas not match!')
        

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import registrationsform
from .models import User
from django.contrib import auth, messages
from django.contrib.auth import login, logout, authenticate

# User Account verification
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import default_token_generator
from carts.models import Cart, CartItem
from carts.views import _cart_id
import requests

#  Create your views here.
def register(request):
    if request.method == 'POST':
        form = registrationsform(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split('@')[0]
            phone_number = form.cleaned_data['phone_number']
            user = User.objects.create_user(first_name=first_name, last_name=last_name, email=email, password=password, username=username)
            user.phone_number = phone_number
            user.is_active = True
            user.save()
            # current_site = get_current_site(request)
            # mail_subject = "Please activate your account"
            # message = render_to_string("accounts/verification_email.html", {
            #     "user": user,
            #     "domain": current_site,
            #     "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            #     "token": default_token_generator.make_token(user)
            # })
            # to_email = email
            # msg = EmailMessage(mail_subject, message, to=[to_email])
            # msg.send()
            # # messages.success(request, "Thank you for registring with us")
            # return redirect("/account/login/?command=verification&email="+email)
            return redirect('/account/login')
    else:
        form = registrationsform()
    context = {'form':form}
    return render(request, 'accounts/register.html', context)

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    for i in cart_item:
                        i.user = user
                        i.save()
            except Cart.DoesNotExist:
                cart = Cart.objects.create(cart_id=_cart_id(request))

            auth.login(request, user)
            messages.success(request, "You are now logged in")
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                params = dict(x.split("=") for x in query.split("&"))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
                
            except:
                return redirect('category:category_view')
        else:
            messages.error(request, "Invalide login credentials")

    return render(request, 'accounts/login.html')

# def activate(request, uidb64, token):
#     try:
#         uid = urlsafe_base64_decode(uidb64).decode()
#         user = User._default_manager.get(pk=uid)
#     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
#         user = None
#     if user is not None and default_token_generator.check_token(user, token):
#         user.is_active = True
#         user.save()
#         messages.success(request, "Congratulations! Your account is activated")
#         return redirect("account:login")
#     else:
#         messages.error(request, "Invalide activation")
#         return redirect("account:register")


def logout(request):
    auth.logout(request)
    messages.success(request, "you're logged out")
    return redirect('/')

# def forgotPassword(request):
#     if request.method == 'POST':
#         email = request.POST['email']
#         if User.objects.filter(email=email).exists():
#             user = User.objects.get(email__exact=email)
#             current_site = get_current_site(request)
#             mail_subject = "Please Reset Your Password"
#             message = render_to_string("accounts/forgot_activate_email.html", {
#                 "user": user,
#                 "domain": current_site,
#                 "uid": urlsafe_base64_encode(force_bytes(user.pk)),
#                 "token": default_token_generator.make_token(user)
#             })
#             to_email = email
#             msg = EmailMessage(mail_subject, message, to=[to_email])
#             msg.send()
#             messages.success(request, "Password reset email has been sent to your email address")
#             return redirect("account:login")
#         else:
#             messages.error(request, "account doesn't exist")
#             return redirect("account:forgotPassword")
#     return render(request, "accounts/forgotPassword.html")

# def password_validate(request, uidb64, token):
#     try:
#         uid = urlsafe_base64_decode(uidb64).decode()
#         user = User._default_manager.get(pk=uid)
#     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
#         user = None
#     if user is not None and default_token_generator.check_token(user, token):
#         request.session['uid'] = uid
#         messages.success(request, "Please reset your password")
#         return redirect("account:resetPassword")
#     else:
#         messages.error(request, "This link has been expired")
#         return redirect("account:login")

# def resetPassword(request):
#     if request.method == 'POST':
#         password = request.POST['password']
#         confirm_password = request.POST['confirm_password']
#         if password == confirm_password:
#             uid = request.session.get('uid')
#             user = User.objects.get(pk=uid)
#             user.set_password(password)
#             user.save()
#             messages.success(request, "password reseted successfuly")
#             return redirect("account:login")
#         else:
#             messages.error(request, "Password do not match")
#             return redirect("account:resetPassword")
#     else:
#         return render(request, "accounts/reset_Password.html")

templates/accounts/forgotPassword.html
{% extends 'base.html' %}

{% block content %}
       <!-- Breadcrumb Start -->
       <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">

                <li class="breadcrumb-item active">Forgot Password</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Login Start -->
    <div class="login">
        <div class="container-fluid">
          <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            {% include "includes/alerts.html" %}
            <form class="" action="{% url 'account:forgotPassword' %}" method="post" style="width:100%; padding:20px">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>E-mail</label>
                        <input class="form-control" type="text" placeholder="E-mail" name='email'>
                    </div>
                    <div class="col-md-12">
                        <button class="btn">Submit</button>
                    </div>
            </form>
                    </div>
                </div>

        </div>
    </div>
    <p class="text-center mt-4">Got Password<a href="{% url 'accounts:login' %}"> Login</a></p>
    <br><br>
</div>
    <!-- Login End -->

{% endblock %}

templates/accounts/forgot_activate_email.html
{% autoescape off%}
Hi {{ user.first_name }}
<h5>Please click on the link to reset your password</h5>
http://{{domain}}{% url 'account:password_validate' uidb64=uid token=token%}
{% endautoescape %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
       <!-- Breadcrumb Start -->
       <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">

                <li class="breadcrumb-item active">Login</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Login Start -->
    <div class="login">
        {% if request.GET.command == 'verification' %}
        <div class="container text-center mx-auto alert alert-info" role="alert" style="max-width:1024px; margin-top:4px">
            Thank you for registering with us, we have sent an email to your email address
            <span class="fst-italic">[{{ request.GET.email }}]</span>
        </div>
        {% else %}
        <div class="container-fluid">
          <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            {% include "includes/alerts.html" %}
            <form class="" action="{% url 'account:login' %}" method="post" style="width:100%; padding:20px">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>E-mail</label>
                        <input class="form-control" type="text" placeholder="E-mail" name='email'>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input class="form-control" type="password" placeholder="Password", name='password'>
                    </div>
                    <div class="col-md-12">
                        <button class="btn">Submit</button>
                    </div>
                    {% comment %} <div class="form-group">
                        <a href="{% url 'account:forgotPassword' %}" class="float-right">Forgot Password?</a>
                    </div> {% endcomment %}
                    {% comment %} <div class="col-md-12">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="newaccount">
                            <label class="custom-control-label" for="newaccount">Keep me signed in</label>
                        </div>
                    </div> {% endcomment %}
            </form>
                    </div>
                </div>

        </div>
    </div>
    <p class="text-center mt-4"> Don't have account?<a href="{% url 'accounts:register' %}"> Sign Up</a></p>
    <br><br>
</div>
{% endif %}
    <!-- Login End -->

{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}


{% block content%}
       <!-- Breadcrumb Start -->
       <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item active"> Register</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->
    <!-- Login Start -->
    <div class="login">
        <div class="container-fluid">
          <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            <form class="" action="{% url 'account:register' %}" method="post">
                {% csrf_token %}
              <div class="register-form">
                {% include "includes/alerts.html" %}
                  <div class="row">
                      <div class="col-md-6">
                          <label>First Name</label>
                          {{ form.first_name }}
                      </div>
                      <div class="col-md-6">
                          <label>Last Name"</label>
                          {{ form.last_name }}
                      </div>
                      <div class="col-md-6">
                          <label>E-mail</label>
                          {{ form.email }}
                      </div>
                      <div class="col-md-6">
                          <label>Mobile No</label>
                          {{ form.phone_number }}
                      </div>
                      <div class="col-md-6">
                          <label>Password</label>
                          {{ form.password }}
                      </div>
                      <div class="col-md-6">
                          <label>Confirm Password</label>
                          {{ form.confirm_password }}
                      </div>
                      <div class="col-md-12">
                          <button class="btn btn-primary btn-block">Submit</button>
                      </div>
                      {{ form.email.errors }}
                      {{ form.non_field_errors }}
            </form>



                    </div>
                </div>

        </div>
        <p class="text-center mt-4">Have an account?
           <a href="{% url 'accounts:login' %}">Log In</a>
        </p>
        <br><br>
    </div>
  </div>
    <!-- Login End -->
{% endblock %}

templates/accounts/reset_Password.html
{% extends 'base.html' %}

{% block content %}
       <!-- Breadcrumb Start -->
       <div class="breadcrumb-wrap">
        <div class="container-fluid">
            <ul class="breadcrumb">

                <li class="breadcrumb-item active">Reset Password</li>
            </ul>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Login Start -->
    <div class="login">
        <div class="container-fluid">
          <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
            {% include "includes/alerts.html" %}
            <form class="" action="{% url 'account:resetPassword' %}" method="post" style="width:100%; padding:20px">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Password</label>
                        <input class="form-control" type="password" placeholder="Create Password" name='password'>
                    </div>
                    <div class="form-group">
                        <label>Confirm Password</label>
                        <input class="form-control" type="password" placeholder="confirm Password", name='confirm_password'>
                    </div>
                    <div class="col-md-12">
                        <button class="btn">Reset Password</button>
                    </div>
            </form>
                    </div>
                </div>

        </div>
    </div>
    <br/><br/>
</div>
    <!-- Login End -->

{% endblock %}

templates/accounts/verification_email.html
{% autoescape off%}
Hi {{ user.first_name }}
<h5>Please click on the link to activate your account</h5>
http://{{domain}}{% url 'account:activate' uidb64=uid token=token%}
{% endautoescape %}