EStore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
    path("product/", include("products.urls", namespace="product")),
    path("category/", include("category.urls", namespace="category")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include('orders.urls', namespace="order")),
    path("about_us/", views.about_us, name="about_us"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_condition/", views.terms_condition, name="terms_condition"),
    path("payment_policy/", views.payment_policy, name="payment_policy"),
    path("shipping_policy/", views.shipping_policy, name="shipping_policy"),
    path("return_policy/", views.return_policy, name="return_policy")



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate"),
    # path("forgotpass/", views.forgotPassword, name="forgotPassword"),
    # path("password_validate/<uidb64>/<token>", views.password_validate, name="password_validate"),
    # path("resetPassword/", views.resetPassword, name="resetPassword")
]

carts/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remote_cart, name='remove_cart'),
    path('checkout/', views.checkout, name="checkout"),
]

microstock/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .import views

app_name = 'order'

urlpatterns = [
    path('place_order', views.place_order, name='place_order'),
    path('payment/', views.payment_view, name='payment'),
    path('success/', views.myorder_view, name='success'),
    path('order/<int:order_id>/download/', views.order_download, name='download'),



]

vendors/urls.py
from django.urls import path
from .views import VendorDashBoard, VendorProduct, VendorTransactions
from products.views import ProductCreateView, ProductUpdateView
app_name = "vendor"

urlpatterns = [
    path("", view=VendorDashBoard.as_view(), name='dashboard'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
    path('product/<slug:slug>/update/', ProductUpdateView.as_view(), name='update'),
    path("product/list/", VendorProduct.as_view(), name='product_list'),
    path("transaction", VendorTransactions.as_view(), name='transaction')
]

vendors/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
# Create your models here.

class Vendor(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.seller.first_name
    
    def get_absolute_url(self):
        view_name = 'product:vendor_detail'
        return reverse(view_name, kwargs={"vendor_name":self.seller.username})

templates/includes/alerts.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div id="message" class="container">
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
            <button class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/includes/footer.html
{% load static %}
<!-- Footer Start -->
<div class="footer">
    <div class="container-fluid">
        <div class="row">
            {% comment %} <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Get in Touch</h2>
                    <div class="contact-info">
                        <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                        <p><i class="fa fa-envelope"></i>email@example.com</p>
                        <p><i class="fa fa-phone"></i>+123-456-7890</p>
                    </div>
                </div>
            </div> {% endcomment %}
            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Seller Info</h2>
                    <ul>
                        {% if request.user.vendor_set.all %}
                        <li><a href="{% url 'vendor:dashboard' %}">Seller Dashboard</a></li>
                        {% comment %} <li><a href="#">Shipping Policy</a></li>
                        <li><a href="#">Return Policy</a></li> {% endcomment %}
                        {% else %}
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'vendor:dashboard' %}">Become a Seller</a></li>
                            {%else%}
                                <li><a href="{% url 'account:login' %}">Become a Seller</a></li>
                            {%endif%}
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Follow Us</h2>
                    <div class="contact-info">
                        <div class="social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Company Info</h2>
                    <ul>
                        <li><a href="{% url 'about_us' %}">About Us</a></li>
                        <li><a href="{% url 'privacy_policy' %}">Privacy Policy</a></li>
                        <li><a href="{%url 'terms_condition' %}">Terms & Condition</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Purchase Info</h2>
                    <ul>
                        <li><a href="{% url 'payment_policy' %}">Pyament Policy</a></li>
                        <li><a href="{% url 'shipping_policy'%}">Shipping Policy</a></li>
                        <li><a href="{% url 'return_policy'%}">Return Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row payment align-items-center">
            <div class="col-md-6">
                <div class="payment-method">
                    <h2>We Accept:</h2>
                    <img src="{% static 'img/payment-method.png' %}" alt="Payment Method" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="payment-security">
                    <h2>Secured By:</h2>
                    <img src="{% static 'img/godaddy.svg' %}" alt="Payment Security" />
                    <img src="{% static 'img/norton.svg' %}" alt="Payment Security" />
                    <img src="{% static 'img/ssl.svg' %}" alt="Payment Security" />
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

<!-- Footer Bottom Start -->
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-6 copyright">
                <p>Copyright &copy; <a href="#">EStore</a>. All Rights Reserved</p>
            </div>

            <div class="col-md-6 template-by">
                <p>Template By <a href="#">EStore</a></p>
            </div>
        </div>
    </div>
</div>
<!-- Footer Bottom End --> 

templates/includes/navbar.html
{% load static%}
<!-- Top bar Start -->
<div class="top-bar">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <i class="fa fa-envelope"></i>
                support@email.com
            </div>
            <div class="col-sm-6">
                <i class="fa fa-phone-alt"></i>
                +012-345-6789
            </div>
        </div>
    </div>
</div>
<!-- Top bar End -->

<!-- Nav Bar Start -->
<div class="nav">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a href="#" class="navbar-brand">MENU</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav mr-auto">
                    <a href="/" class="nav-item nav-link active">Home</a>
                </div>
                <div class="navbar-nav ml-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-user" style="font-size:38px;"><span style="font-size:20px">{{ request.user.first_name}}</span></i>
                        </a>
                        <div class="dropdown-menu">
                            {% if request.user.vendor_set.all %}
                            <a href="{% url 'vendor:product_list' %}" class="dropdown-item">Manage Product</a>
                            <a href="{% url 'vendor:transaction' %}" class="dropdown-item">Sales Report</a>
                            <a href="{% url 'vendor:dashboard' %}" class="dropdown-item">Dashboard</a>
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'order:success'%}" class="dropdown-item">Library</a>
                            <a href="{% url 'account:logout' %}" class="dropdown-item">logout</a>
                            {% else %}
                            <a href="{% url 'account:login' %}" class="dropdown-item">Login</a>
                            <a href="{% url 'account:register' %}" class="dropdown-item">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Nav Bar End -->

<!-- Bottom Bar Start -->
<div class="bottom-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-3">
                <div class="logo">
                    <a href="/">
                        <img src="{% static 'img/logo.png' %}" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="search">
                    <input type="text" name="q" placeholder="Search">
                    <button><i class="fa fa-search"></i></button>
                </div>
            </div>
            <div class="col-md-3">
                <div class="user">
                    <a href="#" class="btn wishlist">
                        <i class="fa fa-heart"></i>
                        <span>(0)</span>
                    </a>
                    <a href="{% url 'cart:cart' %}" class="btn cart">
                        <i class="fa fa-shopping-cart"></i>
                        <span>{{cart_count}}</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Bottom Bar End -->