EStore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
    path("product/", include("products.urls", namespace="product")),
    path("category/", include("category.urls", namespace="category")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include('orders.urls', namespace="order")),
    path("about_us/", views.about_us, name="about_us"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_condition/", views.terms_condition, name="terms_condition"),
    path("payment_policy/", views.payment_policy, name="payment_policy"),
    path("shipping_policy/", views.shipping_policy, name="shipping_policy"),
    path("return_policy/", views.return_policy, name="return_policy")



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remote_cart, name='remove_cart'),
    path('checkout/', views.checkout, name="checkout"),
]

microstock/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendors/urls.py
from django.urls import path
from .views import VendorDashBoard, VendorProduct, VendorTransactions
from products.views import ProductCreateView, ProductUpdateView
app_name = "vendor"

urlpatterns = [
    path("", view=VendorDashBoard.as_view(), name='dashboard'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
    path('product/<slug:slug>/update/', ProductUpdateView.as_view(), name='update'),
    path("product/list/", VendorProduct.as_view(), name='product_list'),
    path("transaction", VendorTransactions.as_view(), name='transaction')
]

vendors/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
# Create your models here.

class Vendor(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.seller.first_name
    
    def get_absolute_url(self):
        view_name = 'product:vendor_detail'
        return reverse(view_name, kwargs={"vendor_name":self.seller.username})

vendors/forms.py
from django import forms

class VendorForm(forms.Form):
    agree = forms.BooleanField(label="Agree to terms", widget=forms.CheckboxInput)

vendors/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from .forms import VendorForm
from vendors.mixins import VendorMixin
from EStore.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.views.generic import ListView
from .models import Vendor
from products.models import Product
from orders.models import Order
# Create your views here.

class VendorProduct(VendorMixin, ListView):
    model = Product
    template_name = 'vendors/product_list_view.html'

    def get_queryset(self, *args, **kwargs):
        qs =  super(VendorProduct, self).get_queryset(*args, **kwargs)
        qs = qs.filter(seller=self.get_vendor())
        return qs



class VendorTransactions(VendorMixin, ListView):
    model = Order
    template_name = 'vendors/transaction_list.html'

    def get_queryset(self):
        return self.get_transaction





class VendorDashBoard(VendorMixin, FormMixin, View):
    form_class = VendorForm
    success_url = '/'
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        form = VendorForm()
        vendor = self.get_vendor()
        exists = vendor
        is_active = None
        context = {}
        if exists:
            is_active = vendor.is_active
        if not exists and not is_active:
            context['title'] = "Apply for Account"
            context['form'] = form
        elif exists and is_active:
            context['title'] = "Vendor Dashboard"
            context['products'] = self.get_product()[:4]
            context['transaction'] = self.get_transaction()[:4]

        else:
            pass
        return render(request, "vendors/dashboard.html", context)
    
    def form_valid(self, form):
        data = super(VendorDashBoard, self).form_valid(form) 
        obj = Vendor.objects.create(seller=self.request.user)
        return data

templates/vendors/dashboard.html
{% extends "base.html" %} {% block content %} {% if form%}
<div class="container">
  <div class="container">
    <h5>Things to do in the marketpalce</h5>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus,
      eligendi?
    </p>
  </div>
  <form action="." method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Submit" />
  </form>
</div>
{% endif %}

<!-- Product List Start -->
<div class="product-view">
  <div class="container-fluid">
    <div class="row">
      {% if products %}
      <div class="col-lg-6">
        <div class="row">
          {% for item in products %}
          <div class="col-md-3">
            <div class="product-item">
              {% comment %}
              <div class="product-title">
                <a href="#">Product Name</a>
                <div class="ratting">
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                </div>
              </div>
              {% endcomment %}
              <div class="product-image">
                <a href="{{ item.get_absolute_url }}">
                  <img
                    src="{{ item.image.url }}"
                    alt="Product Image"
                    style="max-width: 100%; max_height: 200px"
                  />
                </a>
                <div class="product-action">
                  <a href="#"><i class="fa fa-cart-plus"></i></a>
                  <a href="#"><i class="fa fa-heart"></i></a>
                  <a href="#"><i class="fa fa-search"></i></a>
                </div>
              </div>
              {% comment %}
              <div class="product-price">
                <h3><span>$</span>{{item.price}}</h3>
                <a class="btn" href=""
                  ><i class="fa fa-shopping-cart"></i>Buy Now</a
                >
              </div>
              {% endcomment %}
            </div>
          </div>
          {% endfor %}
        </div>
        <a href="{% url 'vendor:product_list' %}" class="btn" >ALL Products</a>
      </div>
      {% endif %} {% if transactions%}
      <div class="col-lg-6">
        <div class="table table-responsive">
          <table class="table table-dark">
            <thead>
              <th>S/N</th>
              <th>Product</th>
              <th>Image</th>
              <th>User</th>
              <th>Total</th>
            </thead>
            {% for instance in transactions %}
            <tbody>
              <td>{{instance}}</td>
              <td>
                <img
                  src="{{ instance.product.image.url }}"
                  alt=""
                  width="100px"
                />
              </td>
              <td>{{instance.user.first_name}}</td>
              <td>{{instance.product.price}}</td>
              <td>{{instance.created_at | timesince }} argo</td>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <a href="{% url 'vendor:transaction' %}" class="btn" >ALL Transactions</a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
<!-- Product List End -->

{% endblock %}

templates/vendors/product_list_view.html
{% extends 'base.html' %}
{% block title %} Vendor Product{% endblock %}
{% block content %}
<div class="container mb-4">
    <div class="table table-responsive">
        <table class="table table-dark">
            <thead>
                <th>S/N</th>
                <th>Product</th>
                <th>Image</th>
                <th>Price</th>
                <th>Update</th>
            </thead>
            {% for instance in object_list %}
            <tbody>
               <td>{{ instance.id }}</td>
               <td>{{instance}}</td>
               <td>
                <img src="{{ instance.image.url }}" alt="" width="100px">
               </td>
               <td>{{instance.price}}</td>
               <td>
                <a href="{% url 'vendor:update' instance.slug %}">Update</a>
               </td>
            </tbody>
            {% endfor %}
        </table>
    </div>
    <div class="text-center">
        <a href="{% url 'vendor:create'%}" class="btn">Add Product</a>
    </div>
</div>
{% endblock %}

templates/vendors/transaction_list.html
{% extends 'base.html' %} {% block title %} Sales Report {% endblock %}
 {% block content %}
 {% if object_list %}
<div class="container mb-4">
  <div class="table table-responsive">
    <table class="table table-dark">
      <thead>
        <th>S/N</th>
        <th>Product</th>
        <th>Image</th>
        <th>User</th>
        <th>Total</th>
      </thead>
      {% for instance in object_list %}
      <tbody>
        <td>{{instance}}</td>
        <td>
          <img src="{{ instance.product.image.url }}" alt="" width="100px" />
        </td>
        <td>{{instance.user.first_name}}</td>
        <td>{{instance.product.price}}</td>
        <td>{{instance.created_at | timesince }} argo</td>
      </tbody>
      {% endfor %}
    </table>
  </div>
</div>
{% else %}
    <div class="text-center">
        <h3>There Is No Transaction In Your Dashboard</h3>
    </div>
{% endif %}
{% endblock %}