EStore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
    path("product/", include("products.urls", namespace="product")),
    path("category/", include("category.urls", namespace="category")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include('orders.urls', namespace="order")),
    path("about_us/", views.about_us, name="about_us"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path("terms_condition/", views.terms_condition, name="terms_condition"),
    path("payment_policy/", views.payment_policy, name="payment_policy"),
    path("shipping_policy/", views.shipping_policy, name="shipping_policy"),
    path("return_policy/", views.return_policy, name="return_policy")



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remote_cart, name='remove_cart'),
    path('checkout/', views.checkout, name="checkout"),
]

category/urls.py
from django.urls import path
from . import views

app_name = 'category'

urlpatterns = [
    path('<slug:slug>/', views.category_product_list, name='category'),
    path('', views.category_view, name='category_view')
]

microstock/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("account/", include('accounts.urls', namespace='accounts')),
    path("vendor/", include("vendors.urls", namespace="vendor")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .import views

app_name = 'order'

urlpatterns = [
    path('place_order', views.place_order, name='place_order'),
    path('payment/', views.payment_view, name='payment'),
    path('success/', views.myorder_view, name='success'),
    path('order/<int:order_id>/download/', views.order_download, name='download'),



]

carts/models.py
from django.db import models
from accounts.models import User
from products.models import Product
from category.models import Category
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.title

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from decimal import Decimal
from django.contrib.auth.decorators import login_required

# Create your views here.


def  _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_to_cart(request, product_id):
    user = request.user
    product = Product.objects.get(id=product_id)
    if request.user.is_authenticated:
        cart_item_exist = CartItem.objects.filter(product=product, user=user).exists()
        if cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, user=user)
        else:
            cart_item = CartItem.objects.create(product=product, quantity=1, user=user)
            cart_item.save()
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
    cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart')

def remote_cart(request, product_id, cart_item_id):
    # cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect("cart:cart")

def cart(request, cart_items=None, total=0):
    try:
        tax = 0
        # total = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for item in cart_items:
            total += item.product.price * item.quantity
        
        tax_rate = Decimal(0.05)
        tax = (total * tax_rate)
        tax = Decimal("%.2f" %(tax))
        grand_total = tax + total
    except ObjectDoesNotExist:
        pass
    context = {
        'cart_items': cart_items,
        'total': total,
        'tax': tax,
        'grand_total': grand_total
    }
    return render(request, 'carts/cart.html', context)

@login_required(login_url='account:login')
def checkout(request, cart_items=None, total=0):
    try:
        tax = 0
        total = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for item in cart_items:
            total += item.product.price * item.quantity
        
        tax_rate = Decimal(0.05)
        tax = (total * tax_rate)
        tax = Decimal("%.2f" %(tax))
        grand_total = tax + total
    except ObjectDoesNotExist:
        pass
    context = {
        'cart_items': cart_items,
        'total': total,
        'tax': tax,
        'grand_total': grand_total
    }
    return render(request, 'carts/checkout.html', context)

templates/carts/cart.html
{% extends 'base.html'%} {% block title%} Cart {% endblock %} {% block content %}
{% load static %}
<!-- Cart Start -->
<div class="cart-page">
  <div class="container-fluid">
    {% if cart_items %}
    <div class="row">
      <div class="col-lg-8">
        <div class="cart-page-inner">
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead class="thead-dark">
                <tr>
                  <th>Product</th>
                  <th>Price</th>
                  {% comment %} <th>Quantity</th>
                  <th>Total</th> {% endcomment %}
                  <th>Remove</th>
                </tr>
              </thead>
              <tbody class="align-middle">
                {% for item in cart_items %}
                <tr>
                  <td>
                    <div class="img">
                      <a href="{{ item.product.get_absolute_url }}"
                        ><img src="{{ item.product.image.url }}" alt="Image"
                      /></a>
                      {% comment %} <p>{{ item.product }}dfdsfsdf</p> {% endcomment %}
                    </div>
                  </td>
                  <td>${{ item.product.price }}</td>
                  {% comment %} <td>
                    <div class="qty">
                      <button class="btn-minus">
                        <i class="fa fa-minus"></i>
                      </button>
                      <input type="text" value="1" />
                      <button class="btn-plus">
                        <i class="fa fa-plus"></i>
                      </button>
                    </div>
                  </td>
                  <td>${{ item.product.price }}</td>{% endcomment %}
                  <td> 
                    <a href="{% url 'cart:remove_cart' item.product.id item.id %}">
                        <button><i class="fa fa-trash"></i></button>
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="cart-page-inner">
          <div class="row">
            <div class="col-md-12">
              <div class="coupon">
                <input type="text" placeholder="Coupon Code" />
                <button>Apply Code</button>
              </div>
            </div>
            <div class="col-md-12">
              <div class="cart-summary">
                <div class="cart-content">
                  <h1>Cart Summary</h1>
                  <p>Sub Total<span>${{total}}</span></p>
                  <p>Tax<span>${{tax}}</span></p>
                  {% comment %} <p>Shipping Cost<span>$1</span></p> {% endcomment %}
                  <h2>Grand Total<span>${{grand_total}}</span></h2>
                </div>
                <div class="cart-btn">
                  <a href="{% url 'category:category_view' %}">
                    <button>Shop More</button>
                    </a>
                    <a href="{% url 'cart:checkout' %}">
                      <button>Checkout</button>
                    </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% else %}
      <div class="text-center m-4">
        <h2 style="text-align:center">Your Shopping Cart Is Empty</h2>
        <a href="{% url 'category:category_view' %}">
            <button class="btn rounded-pill">Continue Shopping</button>
        </a>
      </div>
    {% endif %}
  </div>
</div>
<!-- Cart End -->

{% endblock %}

templates/carts/checkout.html
{% extends 'base.html'%}
{% block title %}
Checkout
{% endblock %}
{% block content %}
        <!-- Checkout Start -->
        <div class="checkout">
            <div class="container-fluid">
                <form action="{% url 'order:place_order' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="checkout-inner">
                                <div class="billing-address">
                                    <h2>Billing Address</h2>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>First Name</label>
                                            <input class="form-control" type="text" name="first_name" placeholder="First Name">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Last Name</label>
                                            <input class="form-control" type="text" name="last_name" placeholder="Last Name">
                                        </div>
                                        <div class="col-md-6">
                                            <label>E-mail</label>
                                            <input class="form-control" type="text" name="email" placeholder="E-mail">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Mobile No</label>
                                            <input class="form-control" type="text" name="phone_number" placeholder="Mobile No">
                                        </div>
                                        <div class="col-md-12">
                                            <label>Address</label>
                                            <input class="form-control" type="text" name="address" placeholder="Address">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Country</label>
                                            <input class="form-control" type="text" placeholder="Country" name="country">
                                        </div>
                                        <div class="col-md-6">
                                            <label>City</label>
                                            <input class="form-control" type="text" name="city" placeholder="City">
                                        </div>
                                        <div class="col-md-6">
                                            <label>State</label>
                                            <input class="form-control" type="text" name="state" placeholder="State">
                                        </div>
                                        <div class="col-md-6">
                                            <label>ZIP Code</label>
                                            <input class="form-control" type="text" placeholder="ZIP Code">
                                        </div>
                                    </div>
                                </div>

                                <div class="shipping-address">
                                    <h2>Shipping Address</h2>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>First Name</label>
                                            <input class="form-control" type="text" placeholder="First Name">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Last Name"</label>
                                            <input class="form-control" type="text" placeholder="Last Name">
                                        </div>
                                        <div class="col-md-6">
                                            <label>E-mail</label>
                                            <input class="form-control" type="text" placeholder="E-mail">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Mobile No</label>
                                            <input class="form-control" type="text" placeholder="Mobile No">
                                        </div>
                                        <div class="col-md-12">
                                            <label>Address</label>
                                            <input class="form-control" type="text" placeholder="Address">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Country</label>
                                            <select class="custom-select">
                                                <option selected>United States</option>
                                                <option>Afghanistan</option>
                                                <option>Albania</option>
                                                <option>Algeria</option>
                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            <label>City</label>
                                            <input class="form-control" type="text" placeholder="City">
                                        </div>
                                        <div class="col-md-6">
                                            <label>State</label>
                                            <input class="form-control" type="text" placeholder="State">
                                        </div>
                                        <div class="col-md-6">
                                            <label>ZIP Code</label>
                                            <input class="form-control" type="text" placeholder="ZIP Code">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="checkout-inner">
                                <div class="checkout-summary">
                                    <table class="table">
                                        <tbody class="align-middle">
                                          {% for item in cart_items %}
                                          <tr>
                                            <td>
                                                <img src="{{ item.product.image.url }}" alt="Image" width="70px"/>
                                            </td>
                                            <td>
                                                <p>{{ item.product }}</p>
                                            </td>
                                            <td>${{ item.product.price }}</td>
                                            {% comment %} <td>
                                              <div class="qty">
                                                <button class="btn-minus">
                                                  <i class="fa fa-minus"></i>
                                                </button>
                                                <input type="text" value="1" />
                                                <button class="btn-plus">
                                                  <i class="fa fa-plus"></i>
                                                </button>
                                              </div>
                                            </td>
                                            <td>${{ item.product.price }}</td>{% endcomment %}
                                          </tr>
                                          {% endfor %}
                                          <tr>
                                            <td colspan="2">Tax</td>
                                            <td>${{tax}}</td>
                                          </tr>
                                          <tr>
                                            <td colspan="2">Grand Total</td>
                                            <td>${{grand_total}}</td>
                                          </tr>
                                        </tbody>
                                      </table>
                                </div>

                                <div class="checkout-payment">
                                    <div class="payment-methods">
                                        <h1>Payment Methods</h1>
                                        <div class="payment-method">
                                            <div class="custom-control custom-radio">
                                                <input type="radio" class="custom-control-input" id="payment-1" name="payment">
                                                <label class="custom-control-label" for="payment-1">Paypal</label>
                                            </div>
                                            <div class="payment-content" id="payment-1-show">
                                                <p>
                                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt orci ac eros volutpat maximus lacinia quis diam.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="checkout-btn">
                                        <button type="submit">Place Order</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- Checkout End -->

{% endblock %}